spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    initialization-mode: never
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: huyhoang
    password: huyhoang