server:
  port: 8080
  servlet:
    context-path: /coffee-shop
  application:
    name: coffee-shop

spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    username: huyhoang
    password: huyhoang
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        ddialect: org.hibernate.dialect.PostgreSQL95Dialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml




